name: "Fast Forward Test Suite"

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  tests:
    uses: php-fast-forward/dev-tools/.github/workflows/tests.yml@main
    with:
      publish-required-statuses: ${{ github.actor != 'dependabot[bot]' }}
    secrets: inherit
